### PR TITLE
Transition from Ubuntu 14.04 to Debian Stretch

### PR DESCRIPTION
**Pull request by maltris**
Since I had problems with lua-expat on Ubuntu 14.04, I did some quick changes to get prosody running on a Debian Stretch-base.

### CODE REVIEW

**Comment by maltris** [comment]
Its still there. :+1:

**Comment by maltris** [comment]
Bump. :wave:

**Comment by mwild1** [comment]
Hey, thanks for the contribution. Sorry for the delay in acknowledging it, I've been away, and the Prosody team have been focused on the upcoming 0.10 release.

Switching the distribution/version here will also require us to update our build server to feed in the correct deb package. On that note, is there a reason you switched from Ubuntu to Debian? Presumably a more recent version of Ubuntu such as 16.04 would have also sufficed.

In any case, I'll need to test this before merging. This is likely to happen after the 0.10 beta release (which we're actively working on) and before the final release.

**Comment by maltris** [comment]
I had a problem running the command with the three environment-variables for user-creation. Also I got this message (still get this, just tried right now with the Ubuntu 14.04-based image). 

```
general             error	The version of LuaExpat on your system does not support stanza size limits, which may leave servers on untrusted networks (e.g. the internet) vulnerable to denial-of-service attacks. You should upgrade to LuaExpat 1.3.0 or higher as soon as possible. See http://prosody.im/doc/depends#luaexpat for more information.
```

Though this could have been fixed by a newer Ubuntu also. Maybe create another branch for the Debian-based image and let the Ubuntu one be? (I was not aware its breaking your development-processes.)

**Comment by maltris** [comment]
Whoops. These commits are not meant to be merged ...

**Pull request closed without merging**
